# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZigazagPuzzle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZigazagPuzzle


  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'FBAudienceNetwork'
  pod 'SwiftyStoreKit'


    target 'ZigazagPuzzleTests' do
      inherit! :search_paths
      # Pods for testing
    end

    target 'ZigazagPuzzleUITests' do
      # Pods for testing
    end

  end

